# Generated by Django 4.2.10 on 2026-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science Engineering'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('it', 'Information Technology'), ('aiml', 'Artificial Intelligence & Machine Learning'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
